# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20170927_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='designation',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
